### ISSUE TITLE
DINTO

### ISSUE THREAD

**Issue by GoogleCodeExporter** [OBOFoundry/Operations-Committee-RETIRED#176]
```
Dear OBO Foundry members,

We have extended the first version of the Drug-Drug Interactions Ontology 
(DINTO). DINTO 1.2 includes information about adverse drug reactions (ADRs) and 
their relationships to pharmacological entities included in the ontology.

To create this version, we have imported a reduced version of the Ontology for 
Adverse Events  (OAE version 1.1.247), including only the top class 'adverse 
event' and its subclasses. This reduced subset of OAE can be downloaded from 
https://drive.google.com/folderview?id=0B-7Po9tR1KLUUDZPRkFGOFFmVjA&usp=sharing.

In addition to this, we have imported drug-ADR relationships for the database 
SIDER , which can be used with SWRL rules to infer DDIs occurring by the 
addition of a common ADR.


We would like to request the review of this new realease by the OBO Foundry, 
and the update of this version instead of the previous one at the OBO Foundry 
website.

DINTO 1.2 can be downloaded from https://code.google.com/p/dinto/



Description of the resource to review:

-ontology name: The Drug-Drug Interactions Ontology (DINTO)

-contact person name: Maria Herrero

-contact person email: asmarahz84@gmail.com; mariahz@pa.uc3m.es

-scope of ontology: Drug-drug interactions and related aspects

-link to stable version of the ontology:https://code.google.com/p/dinto/

-link to ontology documentation (e.g., web or wiki 
page):https://code.google.com/p/dinto/

-other important links (describe):-

-date of previous review request (if applicable):-


Kind regards,

María



```

Original issue reported on code.google.com by `mhzazo@gmail.com` on 16 Jun 2015 at 4:32

**Comment by ramonawalls** [comment]
Comment from MHerrero that was made on Google Code after the migration:

Hello,

I will answer to your questions below:

1.Yes, we would like to request a formal review of DINTO.
1. Could you please let me know if I should create a new purl for the version 1.2, or modify the existing one?
2. We will move the DINTO repository to GitHub, as you suggested.

Thank you very much,

Maria

**Comment by ramonawalls** [comment]
Maria - 
Please paste the link to the new ontology repo here.
As for the PURLS, you can continue to point the PURLs for older versions to your old repo, but I suggest that you move them to your new repo and redirect the PURLs there. There should be a separate PURL for each release (i.e. version). See this page (http://obofoundry.github.io/id-policy.html) for more details.

**Comment by labda** [comment]
Hello,

The link to the new ontology repo is:
https://github.com/labda/DINTO

We have modified the PURL, so it redirects to the github repository.

We have created PURLS for the two versions:
http://purl.obolibrary.org/obo/dinto/2014-06-25/dinto.owl
http://purl.obolibrary.org/obo/dinto/2015-06-01/dinto.owl

Please, let us know any further step,

Kind regards,

Maria

**Comment by ramonawalls** [comment]
Thanks for the update. Normally, the PURLs for both versions should point directly to the raw version of the file, so they can be opened directly from the PURL. 
For example:
http://purl.obolibrary.org/obo/dinto/2014-06-25/dinto.owl 
should point to 
https://raw.githubusercontent.com/labda/DINTO/master/DINTO%201/DINTO_1.owl

However, I see this is a problem with version 2, because it  the files may be too large for Github and you are currently storing it as a zipped file. Even version 1 cannot be opened in Protege directly from the URL. In this case, maybe Github is not the ideal repository for your files. 

Is there a reason that the ontology is so large? Are you importing a lot of large external ontologies? Is it just because you have so many classes? A better approach might be to make the ontology modular, so that the main ontology just includes DINTO classes and scripts to import external files (like the OAE subset).

**Comment by ramonawalls** [comment]
A preliminary review suggested that DINTO does not comply adequately with some of the OBO Foundry principles. We have asked the developers to make some changes and re-do the self-assessment when they are ready.

Closing this issue for now. Will re-open when a new self-assessment is submitted.

**Comment by ramonawalls** [comment]
See pre-review at https://docs.google.com/document/d/16ZCwEmWuv9eYzilm0VKPb-QjupKfn5l_R7RZVlIryTs/edit
